def confusion_matrix(true, eval):
    tn, fp, fn, tp = 0,0,0,0
    for t, e in zip(true, eval):
        if t == True and e == True:
            tp += 1
        if t == True and e == False:
            fn += 1
        if t == False and e == True:
            fp += 1
        if t == False and e == False:
            tn += 1

    return tn, fp, fn, tp

# extracted results from each methods.
# method[i][j] : result of player i's jth game from "method"
true = [[False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True], [False, False, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True]]

th_VacA = [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False]]
th_AccA = [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False]]
th_Kill = [[False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True], [False, False, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False], [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True], [False, False, False, False, False, False, False, True, True, True, True]]
ks_AccA = [[False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True], [True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True]]
os_CAC = [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, True, True, True, True], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False]]
os_LAC = [[False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False,False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, True, True], [False, False, False, False, False, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True]]
os_SMAC = [[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True], [False, False, False, False, False, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, False, False, False, False, False], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True], [True, True, True, True, True, True, True, True, True, True, True]]
botscreen = [[False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True], [False, False, False, False, False, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, True, True, True, True, True, True, True, True, True], [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True], [False, False, False, False, False, False, True, True, True, True], [False, False, False, False, True, True, True, True, True, True, True]]

print("th_VacA")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], th_VacA[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))
    
print("th_AccA")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], th_AccA[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("th_Kill")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], th_Kill[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("ks_AccA")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], ks_AccA[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("os_CAC")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], os_CAC[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("os_LAC")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], os_LAC[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("os_SMAC")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], os_SMAC[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))

print("botscreen")
for i in range(14):
    tn, fp, fn, tp = confusion_matrix(true[i], botscreen[i])
    print("%.3f (%d/%d/%d)"%((tn+tp)/(tn+fp+fn+tp), fp, fn, tn+fp+fn+tp))
    
